# Generated by Django 2.2.2 on 2019-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanUsaha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemohon', models.CharField(max_length=25)),
                ('nomor_induk', models.IntegerField()),
            ],
        ),
    ]
