# Generated by Django 2.2.2 on 2019-06-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonanusaha',
            name='deskripsi_usaha',
            field=models.TextField(default='bisnis digital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permohonanusaha',
            name='nama_usaha',
            field=models.CharField(default='kotobox', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permohonanusaha',
            name='verifikasi',
            field=models.BooleanField(default=False),
        ),
    ]
