# Generated by Django 2.2.2 on 2019-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0002_auto_20190620_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonanusaha',
            name='foto',
            field=models.ImageField(default='person.png', upload_to='layanan/izin-usaha/foto'),
        ),
    ]
