# Generated by Django 2.2.2 on 2019-06-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0003_permohonanusaha_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrasiKTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=35)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(choices=[('islam', 'islam'), ('Kristen Katolik', 'Kristen Katolik'), ('Kristen Protestan', 'Kristen Protestan'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Kong Hu Cu', 'Kong Hu Cu')], max_length=17)),
                ('status_perkawinan', models.CharField(choices=[('1', 'Belum Kawin'), ('2', 'Kawin'), ('3', 'Cerai')], max_length=11)),
                ('pekerjaan', models.CharField(max_length=45)),
                ('pilihan_status_wn', models.CharField(choices=[('WNI', 'WARGA NEGARA INDONESIA'), ('WNA', 'WARGA NEGARA ASING')], max_length=3)),
                ('waktu_pembuatan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
