# Generated by Django 2.2.2 on 2019-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0004_administrasiktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasiktp',
            name='alamat',
            field=models.TextField(default='jalan jatiarum F3 No.12'),
            preserve_default=False,
        ),
    ]
