# Generated by Django 2.2.2 on 2019-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0005_administrasiktp_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrasiktp',
            name='status_perkawinan',
            field=models.CharField(choices=[('Belum Menikah', 'Belum Menikah'), ('Menikah', 'Menikah'), ('Cerai', 'Cerai')], max_length=11),
        ),
    ]
