# Generated by Django 2.2.2 on 2019-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0006_auto_20190625_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrasiktp',
            name='agama',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen Katolik', 'Kristen Katolik'), ('Kristen Protestan', 'Kristen Protestan'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Kong Hu Cu', 'Kong Hu Cu')], max_length=17),
        ),
    ]
