# Generated by Django 2.2.2 on 2019-06-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_publik', '0007_auto_20190625_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerizinanAcara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketuapanitia', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('nama_kegiatan', models.CharField(max_length=55)),
                ('deskripsi_kegiatan', models.TextField()),
                ('tanggal_kegiatan', models.DateField()),
                ('waktu_kegiatan', models.TimeField()),
                ('tempat_kegiatan', models.CharField(max_length=50)),
                ('waktu_pembuatan_laporan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
